---
title: "manuscript"
author: "Andrew"
date: "12/17/2020"
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
    pandoc_args: ["--number-offset=2"]
---

This file should be run after running ~/python/scripts/Data Wrangler.ipynb.
It completes the remainder of data wrangling by adding statistical measure columns.

```{r setup, include=FALSE}
# these options here change the formatting of how comments are rendered
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>",
                      results = "hold",
                      fig.show = "hold")

# Clear any existing variables
rm(list = ls())
```

```{r libraries, message=FALSE}
library(tidyverse)
library(glue)
library(lme4)
```


# Load data

```{r}
subject_data = read_tsv("../data/processed/subject_data.tsv")
puzzle_data = read_tsv("../data/processed/puzzle_data.tsv")
```

# Last trial accuracy

```{r}
df = puzzle_data %>% 
  mutate(ltrial = log2(trial))

sigmoid = function(x) {
  return (1 / (1 + exp(-x)))
}

p1_last_acc = glmer(correct ~ ltrial + (ltrial | subject_id),
                    family = "binomial",
                    data = df %>% filter(phase == 1)) %>%
  broom.mixed::augment() %>% 
  group_by(subject_id) %>% 
  filter(ltrial == max(ltrial)) %>%
  mutate(p1_last_acc = sigmoid(.fitted)) %>% 
  select(subject_id, p1_last_acc)

p2_last_acc = glmer(correct ~ ltrial + (ltrial | subject_id),
                    family = "binomial",
                    data = df %>% filter(phase == 2)) %>%
  broom.mixed::augment() %>% 
  group_by(subject_id) %>% 
  filter(ltrial == max(ltrial)) %>%
  mutate(p2_last_acc = sigmoid(.fitted)) %>% 
  select(subject_id, p2_last_acc)
```

# Overall accuracy
```{r}
accuracy = puzzle_data %>% 
  group_by(subject_id, phase) %>% 
  summarize(accuracy = mean(correct)) %>% 
  pivot_wider(id_cols = subject_id,
              names_from = phase,
              names_glue = "p{phase}_{.value}",
              values_from = accuracy)
```

# Non-modal digit responses
```{r}
p2_non_md = puzzle_data %>% 
  filter(phase == 2,
         response_type != 'target',
         response_type != 'distractor') %>% 
  group_by(subject_id) %>% 
  summarize(p2_non_md = n())
```

# Solved in last 8 trials of phase 2
```{r}
p2_last_8_solved = puzzle_data %>% 
  filter(phase == 2,
         trial > 56) %>% 
  group_by(subject_id) %>% 
  summarize(p2_last_8_solved = sum(correct))
```

# Combine data and save

```{r}
solver_boundary = .8 

subject_data = subject_data %>% 
  merge(accuracy, all.x = T) %>% 
  merge(p1_last_acc, all.x = T) %>% 
  merge(p2_last_acc, all.x = T) %>% 
  merge(p2_non_md, all.x = T) %>% 
  merge(p2_last_8_solved, all.x = T) %>% 
  arrange(desc(p1_last_acc), desc(p2_accuracy), sid_hash) %>% 
  mutate(subject_id_old = subject_id, # remap based on p1_last_acc
         subject_id = 1:nrow(subject_data),
         solver = p1_last_acc >= solver_boundary,
         excluded = is.na(tut_house),
         p2_non_md = replace_na(p2_non_md, 0),
         p2_last_8_solved = replace_na(p2_last_8_solved, 0),
         q_puzzle_digit = replace_na(q_puzzle_digit, 0))

sid_map = subject_data %>% 
  select(subject_id_old, subject_id)

subject_data = subject_data %>% 
  select(-subject_id_old) %>% 
  select(subject_id, sid_hash, excluded, solver, p1_accuracy, p2_accuracy,
         p1_last_acc, p2_last_acc, p2_non_md, p2_last_8_solved, everything())

puzzle_data = puzzle_data %>% 
  rename(subject_id_old = subject_id) %>% # remap based on p1_last_acc
  merge(sid_map) %>% 
  select(-subject_id_old) %>% 
  select(subject_id, everything()) %>% 
  arrange(subject_id, phase, trial)
```

```{r}
write_tsv(subject_data, "../data/processed/subject_data.tsv")
write_tsv(puzzle_data, "../data/processed/puzzle_data.tsv")
```

# For questionnaire rating

```{r}
set.seed(1)

df = subject_data %>% 
  filter(!solver,
         p2_last_acc <= .6,
         p2_non_md <= 6,
         p2_last_8_solved >= 3,
         p2_last_8_solved <= 5) 

df = subject_data %>% 
  filter(solver,
         p2_last_acc >= .8) %>% 
  rbind(df) %>% 
  mutate(subject_id = sample(1:nrow(.))) %>% 
  arrange(subject_id) %>% 
  mutate(correct = ifelse(q_puzzle == 'target', 'Correct', 'Incorrect')) 
```

## Pilot raters
```{r}
set.seed(2)

df1 = df %>% 
  filter(solver,
         correct == 'Correct') %>% 
  sample_n(9)

df2 = df %>% 
  filter(solver,
         correct == 'Incorrect') %>% 
  sample_n(1)

df3 = df %>% 
  filter(!solver,
         correct == 'Correct') %>% 
  sample_n(6)

df4 = df %>% 
  filter(!solver,
         correct == 'Incorrect') %>% 
  sample_n(4)

qrater_pilot = df1 %>% 
  rbind(df2) %>% 
  rbind(df3) %>% 
  rbind(df4) %>% 
  mutate(subject_id = sample(1:nrow(.))) %>% 
  arrange(subject_id) %>% 
  select(subject_id, sid_hash, q_puzzle_digit, correct, q_strategy)

qrater_pilot %>% 
  write_tsv("../data/processed/qrater_pilot.tsv")
```

All participants
```{r}
df %>% 
  select(subject_id, sid_hash, q_puzzle_digit, correct, q_strategy) %>%
  filter(!(sid_hash %in% qrater_pilot$sid_hash)) %>% 
  bind_rows(qrater_pilot, .) %>% 
  mutate(subject_id = seq(1, nrow(.))) %>% 
  write_tsv("../data/processed/qrater.tsv")
```